login:
    path:     /login
    defaults: { _controller: ManagementUserBundle:Default:index }

signup:
    path:     /signup
    defaults: { _controller: ManagementUserBundle:Default:signup}

dashboard:
    path:    /dashboard
    defaults: { _controller: ManagementUserBundle:Default:dashboard}

checkuser:
    path:    /checkuser
    defaults: { _controller: ManagementUserBundle:User:checkUser}
    requirements:

saveuser:
    path:    /saveuser
    defaults: { _controller: ManagementUserBundle:User:saveUser}
    requirements:

logout2:
    path:    /logout2
    defaults: { _controller: ManagementUserBundle:User:logoutUser}
    requirements:

updateuser:
    path:    /updateuser
    defaults: { _controller: ManagementUserBundle:User:updateUser}
    requirements:

changepass:
    path:    /changepass
    defaults: { _controller: ManagementUserBundle:Default:changePass}
    requirements:

updatepass:
    path:    /updatepass
    defaults: {_controller: ManagementUserBundle:User:updatePass}

activate:
    path:    /activate
    defaults: {_controller: ManagementUserBundle:Default:activateAccount}

forgotpass:
    path:    /forgotpass
    defaults: {_controller: ManagementUserBundle:Default:forgotPass}

saveforgotpass:
    path:    /saveforgotpass
    defaults: {_controller: ManagementUserBundle:User:saveUserConfirmation}

test:
    path:    /test
    defaults: {_controller: ManagementUserBundle:Default:test}

resetpassword:
    path:    /resetpassword
    defaults: {_controller: ManagementUserBundle:Default:resetPass}

login_check:
    path: /login_check

logout:
    pattern: /logout


